kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chart-verifier-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chart-verifier-admin
subjects:
  - kind: ServiceAccount
    name: chart-verifier-admin
    namespace: prod-chart-verifier-infra
